### ISSUE TITLE
lneqSucc n does not terminate for n > 0

### ISSUE THREAD

**Issue by erisco** [konn/type-natural#11]
Actual:

    > case lneqSucc (SS SZ) of Witness -> "Hello sailor!"
    "

Expected:

    > case lneqSucc (SS SZ) of Witness -> "Hello sailor!"
    "Hello sailor!"

Tested on `type-natural 0.7.1.2` and `GHCi 8.0.1`.

**Comment by konn** [comment]
Good catch. Thanks!
